### ISSUE TITLE
IDMSKconv

### ISSUE THREAD

**Issue by sdomermpc** [superfan89/IDMSKconv#1]
buddy help me extract XML from this Longman Advanced American Dictionary
http://rghost.net/52258765

i have never used python, i tried it on my windows xp, but it always give syntax error

**Comment by superfan89** [comment]
The script is very easy to use, what you need is to install a python 2.7 interpreter and use the command:

```
python IDMSKconv.py [Output dir] [Dictionary dir]
```

If your dictionary is built with IDM, you'll get a bunch of XML files and other stuff. Then you can process the XMLs with your favourite tools.
